In [1]:
import numpy as np
import pandas as pd

In [2]:
research1 = pd.read_csv('research1.csv')
research2 = pd.read_csv('research2.csv')
   

In [3]:
research = research1.merge(research2,on='titles')

In [4]:
research.head()


titles  \
0  Survey on Semantic Stereo Matching / Semantic ...   
1  Survey on Semantic Stereo Matching / Semantic ...   
2  Survey on Semantic Stereo Matching / Semantic ...   
3  Survey on Semantic Stereo Matching / Semantic ...   
4  Survey on Semantic Stereo Matching / Semantic ...   

                                           summaries             terms_x  \
0  Stereo matching is one of the widely used tech...  ['cs.CV', 'cs.LG']   
1  Stereo matching is one of the widely used tech...  ['cs.CV', 'cs.LG']   
2  Stereo matching is one of the widely used tech...  ['cs.CV', 'cs.LG']   
3  Stereo matching is one of the widely used tech...  ['cs.CV', 'cs.LG']   
4  Stereo matching is one of the widely used tech...  ['cs.CV', 'cs.LG']   

              terms_y                                          abstracts  
0  ['cs.CV', 'cs.LG']  Stereo matching is one of the widely used tech...  
1  ['cs.CV', 'cs.LG']  Stereo matching is one of the widely used tech...  
2  ['cs.CV', 'cs.LG']  Stereo matching is one of the widely used tech...  
3  ['cs.CV', 'cs.LG']  Stereo matching is one of the widely used tech...  
4  ['cs.CV', 'cs.LG']  Stereo matching is one of the widely used tech...

In [5]:
column_name = 'terms_y'
research.drop(columns=[column_name], inplace=True)

In [6]:
df = research.drop_duplicates(subset=['titles'])

In [7]:
df.head()


titles  \
0   Survey on Semantic Stereo Matching / Semantic ...   
9   Enforcing Mutual Consistency of Hard Regions f...   
13  Parameter Decoupling Strategy for Semi-supervi...   
17  Background-Foreground Segmentation for Interio...   
26  EdgeFlow: Achieving Practical Interactive Segm...   

                                            summaries             terms_x  \
0   Stereo matching is one of the widely used tech...  ['cs.CV', 'cs.LG']   
9   In this paper, we proposed a novel mutual cons...  ['cs.CV', 'cs.AI']   
13  Consistency training has proven to be an advan...           ['cs.CV']   
17  To ensure safety in automated driving, the cor...  ['cs.CV', 'cs.LG']   
26  High-quality training data play a key role in ...  ['cs.CV', 'cs.HC']   

                                            abstracts  
0   Stereo matching is one of the widely used tech...  
9   In this paper, we proposed a novel mutual cons...  
13  Consistency training has proven to be an advan...  
17  To ensure safety in automated driving, the cor...  
26  High-quality training data play a key role in ...

In [8]:
df_sampled = df.sample(frac=0.1)

In [9]:
df_sampled.head()

titles  \
28017  FPGA/DNN Co-Design: An Efficient Design Method...   
40875  Joint Architecture and Knowledge Distillation ...   
23994  CoDeNet: Efficient Deployment of Input-Adaptiv...   
19577              Semantic Pyramid for Image Generation   
41911  Forming Local Intersections of Projections for...   

                                               summaries  \
28017  While embedded FPGAs are attractive platforms ...   
40875  The technique of distillation helps transform ...   
23994  Deploying deep learning models on embedded sys...   
19577  We present a novel GAN-based model that utiliz...   
41911  In this paper, we propose a novel image descri...   

                    terms_x                                          abstracts  
28017             ['cs.CV']  While embedded FPGAs are attractive platforms ...  
40875             ['cs.CV']  The technique of distillation helps transform ...  
23994  ['cs.CV', 'eess.IV']  Deploying deep learning models on embedded sys...  
19577    ['cs.CV', 'cs.LG']  We present a novel GAN-based model that utiliz...  
41911             ['cs.CV']  In this paper, we propose a novel image descri...

In [13]:
# Reset the index of the DataFrame to start from 0
dp = df_sampled.reset_index(drop=True)

# Print the reordered DataFrame
print(dp)


                                                 titles  \
0     FPGA/DNN Co-Design: An Efficient Design Method...   
1     Joint Architecture and Knowledge Distillation ...   
2     CoDeNet: Efficient Deployment of Input-Adaptiv...   
3                 Semantic Pyramid for Image Generation   
4     Forming Local Intersections of Projections for...   
...                                                 ...   
3881  Perceptual uniform descriptor and Ranking on m...   
3882  Self-Supervised Representation Learning via Ne...   
3883  Fourier Transform of Percoll Gradients Boosts ...   
3884                 Adversarial Dropout Regularization   
3885  Sampling Techniques for Large-Scale Object Det...   

                                              summaries               terms_x  \
0     While embedded FPGAs are attractive platforms ...             ['cs.CV']   
1     The technique of distillation helps transform ...             ['cs.CV']   
2     Deploying deep learning models on embedded

In [14]:
dp.head()

titles  \
0  FPGA/DNN Co-Design: An Efficient Design Method...   
1  Joint Architecture and Knowledge Distillation ...   
2  CoDeNet: Efficient Deployment of Input-Adaptiv...   
3              Semantic Pyramid for Image Generation   
4  Forming Local Intersections of Projections for...   

                                           summaries               terms_x  \
0  While embedded FPGAs are attractive platforms ...             ['cs.CV']   
1  The technique of distillation helps transform ...             ['cs.CV']   
2  Deploying deep learning models on embedded sys...  ['cs.CV', 'eess.IV']   
3  We present a novel GAN-based model that utiliz...    ['cs.CV', 'cs.LG']   
4  In this paper, we propose a novel image descri...             ['cs.CV']   

                                           abstracts  
0  While embedded FPGAs are attractive platforms ...  
1  The technique of distillation helps transform ...  
2  Deploying deep learning models on embedded sys...  
3  We present a novel GAN-based model that utiliz...  
4  In this paper, we propose a novel image descri...

In [15]:
dp.duplicated().sum()

0

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

In [17]:
dp['text'] = dp['titles'] + ' ' + dp['summaries'] + ' ' + dp['abstracts'] + ' ' + dp['terms_x'] 

In [18]:
dp.head()

titles  \
0  FPGA/DNN Co-Design: An Efficient Design Method...   
1  Joint Architecture and Knowledge Distillation ...   
2  CoDeNet: Efficient Deployment of Input-Adaptiv...   
3              Semantic Pyramid for Image Generation   
4  Forming Local Intersections of Projections for...   

                                           summaries               terms_x  \
0  While embedded FPGAs are attractive platforms ...             ['cs.CV']   
1  The technique of distillation helps transform ...             ['cs.CV']   
2  Deploying deep learning models on embedded sys...  ['cs.CV', 'eess.IV']   
3  We present a novel GAN-based model that utiliz...    ['cs.CV', 'cs.LG']   
4  In this paper, we propose a novel image descri...             ['cs.CV']   

                                           abstracts  \
0  While embedded FPGAs are attractive platforms ...   
1  The technique of distillation helps transform ...   
2  Deploying deep learning models on embedded sys...   
3  We present a novel GAN-based model that utiliz...   
4  In this paper, we propose a novel image descri...   

                                                text  
0  FPGA/DNN Co-Design: An Efficient Design Method...  
1  Joint Architecture and Knowledge Distillation ...  
2  CoDeNet: Efficient Deployment of Input-Adaptiv...  
3  Semantic Pyramid for Image Generation We prese...  
4  Forming Local Intersections of Projections for...

In [19]:
tfidf_vectorizer = TfidfVectorizer(stop_words='english')

In [21]:
tfidf_matrix = tfidf_vectorizer.fit_transform(dp['text'])

In [22]:
dp.head()

titles  \
0  FPGA/DNN Co-Design: An Efficient Design Method...   
1  Joint Architecture and Knowledge Distillation ...   
2  CoDeNet: Efficient Deployment of Input-Adaptiv...   
3              Semantic Pyramid for Image Generation   
4  Forming Local Intersections of Projections for...   

                                           summaries               terms_x  \
0  While embedded FPGAs are attractive platforms ...             ['cs.CV']   
1  The technique of distillation helps transform ...             ['cs.CV']   
2  Deploying deep learning models on embedded sys...  ['cs.CV', 'eess.IV']   
3  We present a novel GAN-based model that utiliz...    ['cs.CV', 'cs.LG']   
4  In this paper, we propose a novel image descri...             ['cs.CV']   

                                           abstracts  \
0  While embedded FPGAs are attractive platforms ...   
1  The technique of distillation helps transform ...   
2  Deploying deep learning models on embedded sys...   
3  We present a novel GAN-based model that utiliz...   
4  In this paper, we propose a novel image descri...   

                                                text  
0  FPGA/DNN Co-Design: An Efficient Design Method...  
1  Joint Architecture and Knowledge Distillation ...  
2  CoDeNet: Efficient Deployment of Input-Adaptiv...  
3  Semantic Pyramid for Image Generation We prese...  
4  Forming Local Intersections of Projections for...

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

In [24]:
from sklearn.metrics.pairwise import cosine_similarity
from scipy.sparse import csr_matrix

In [25]:
tfidf_vectorizer = TfidfVectorizer(stop_words='english')

In [26]:
tfidf_matrix = tfidf_vectorizer.fit_transform(dp['text'])

In [27]:
cosine_sim_sparse = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [28]:
tfidf_matrix = tfidf_vectorizer.fit_transform(dp['text'])

In [29]:

cosine_sim_sparse = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [30]:
print(cosine_sim_sparse)

[[1.         0.03607591 0.08752257 ... 0.00447055 0.01721697 0.03120857]
 [0.03607591 1.         0.06208572 ... 0.02601077 0.03938713 0.02023015]
 [0.08752257 0.06208572 1.         ... 0.02812136 0.02498648 0.04024329]
 ...
 [0.00447055 0.02601077 0.02812136 ... 1.         0.05979951 0.02327107]
 [0.01721697 0.03938713 0.02498648 ... 0.05979951 1.         0.01073517]
 [0.03120857 0.02023015 0.04024329 ... 0.02327107 0.01073517 1.        ]]


In [37]:
def recommend_paper(title, cosine_sim_sparse=cosine_sim_sparse):
    filtered_df = dp[dp['titles'] == title]
    if filtered_df.empty:
        print("No paper with the title '{}' found.".format(title))
        return None
    
    idx = filtered_df.index[0]
    sim_scores = list(enumerate(cosine_sim_sparse[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:11]  # Top 10 similar papers
    paper_indices = [i[0] for i in sim_scores]
    return dp.iloc[paper_indices]

In [38]:
first_paper_title = dp.iloc[0]['titles']
print("Title of the first research paper:", first_paper_title)


Title of the first research paper: FPGA/DNN Co-Design: An Efficient Design Methodology for IoT Intelligence on the Edge


In [39]:
recommendations = recommend_paper('FPGA/DNN Co-Design: An Efficient Design Methodology for IoT Intelligence on the Edge')

In [40]:
print(recommendations[['titles']])

                                                 titles
995   SkyNet: A Champion Model for DAC-SDC on Low Po...
983   Structure of Deep Neural Networks with a Prior...
3732  Utilizing Explainable AI for Quantization and ...
627   Uncertainty Propagation in Deep Neural Network...
2125  Automated Design Space Exploration for optimis...
2328  Efficient Algorithms for Device Placement of D...
860   Energy-Efficient Model Compression and Splitti...
1322        Frequency learning for image classification
2757  Efficient non-uniform quantizer for quantized ...
1903                     Efficient Deep Neural Networks


In [41]:
import pickle

In [43]:
pickle.dump(dp,open('research.pkl','wb'))

In [45]:
dp['titles'].values

array(['FPGA/DNN Co-Design: An Efficient Design Methodology for IoT Intelligence on the Edge',
       'Joint Architecture and Knowledge Distillation in CNN for Chinese Text Recognition',
       'CoDeNet: Efficient Deployment of Input-Adaptive Object Detection on Embedded FPGAs',
       ...,
       'Fourier Transform of Percoll Gradients Boosts CNN Classification of Hereditary Hemolytic Anemias',
       'Adversarial Dropout Regularization',
       'Sampling Techniques for Large-Scale Object Detection from Sparsely Annotated Objects'],
      dtype=object)

In [46]:
pickle.dump(dp.to_dict(),open('research_dict.pkl','wb'))

In [47]:
pickle.dump(similarity,open('similarity.pkl','wb'))

NameError: name 'similarity' is not defined

In [48]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [54]:
vectors = cv.fit_transform(dp['text']).toarray()

In [55]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 2, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [56]:
from sklearn.metrics.pairwise import cosine_similarity

In [57]:
similarity = cosine_similarity(vectors)

In [59]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(995, 0.48181241135848574),
 (983, 0.2715163922647971),
 (860, 0.26338624147983497),
 (2125, 0.23987489501504408),
 (823, 0.2385097563090336)]

In [67]:
def recommend(res):
    research_index = dp[dp['titles'] == res].index[0]
    distances = similarity[research_index]
    research_list = sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]
    for i in research_list:
        print(dp.iloc[i[0]].titles)

In [68]:
recommend('FPGA/DNN Co-Design: An Efficient Design Methodology for IoT Intelligence on the Edge')

SkyNet: A Champion Model for DAC-SDC on Low Power Object Detection
Structure of Deep Neural Networks with a Priori Information in Wireless Tasks
Energy-Efficient Model Compression and Splitting for Collaborative Inference Over Time-Varying Channels
Automated Design Space Exploration for optimised Deployment of DNN on Arm Cortex-A CPUs
Piracy-Resistant DNN Watermarking by Block-Wise Image Transformation with Secret Key


In [69]:
pickle.dump(similarity,open('similarity.pkl','wb'))